apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lm8nq7eyn-nodejs
  janus-idp.io/tekton: lm8nq7eyn-nodejs
  backstage.io/kubernetes-id: lm8nq7eyn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lm8nq7eyn-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
